name: work_1

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'work_1/**'
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Show hello message
        run: echo "Hello CI!"
